### ISSUE TITLE
Node.js version problem?

### ISSUE THREAD

**Issue by stevebidondo** [amiracle/grand_central#3]
Anyone seeing this on stack creation for Config Lambda functions?

The following resource(s) failed to create: [ConfigurationRecorderSanitiser, ConfigNotificationEventRule]: ConfigurationRecorderSanitiser

`The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c09f9002-ae45-426e-a47c-2e796e0313b0)`

Update of runtime variables for node here? https://github.com/amiracle/grand_central/blob/1b82f7917a68493670b9e65a043531d2ecc2dff6/bin/botocore/data/lambda/2015-03-31/service-2.json

**Comment by stevebidondo** [comment]
oh man, nodejs8.10 deprecated about a week ago: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by amiracle** [comment]
We are working to resolve this issue. The tests of the code and the lambda functions are being done and a fix will be issued once it's resolved.

**Comment by amiracle** [comment]
This issue has been fixed in version 1.1.1.

**Comment by stevebidondo** [comment]
Hmmm, updated to 1.1.1 but still see the stack failure on generation.

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: fa69bf8e-a168-4a43-8aaa-ef392dde46e9)
